name = "cerno-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "CERNO_KV"
id = "d22c19ad9db1485196d79e3cce159e43"
preview_id = "a27022eb296b4efc81499210ad4df658"
